#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 4 ]]; then
  echo "usage: $0 <tap-directory> <version> <intel-sha256> <arm-sha256>" >&2
  exit 1
fi

tap_directory=$1
version=$2
intel_sha256=$3
arm_sha256=$4

mkdir -p "$tap_directory/Casks"

cat > "$tap_directory/Casks/digg.rb" <<EOF
# This file is generated by digg's release workflow. DO NOT EDIT.
cask "digg" do
  version "${version}"

  on_macos do
    on_intel do
      sha256 "${intel_sha256}"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "${arm_sha256}"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "digg"
  desc "Modern DNS lookup CLI"
  homepage "https://github.com/dantech2000/digg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digg"
  manpage "digg.1"
  binary "completions/digg.bash", target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/digg"
  binary "completions/_digg", target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_digg"
  binary "completions/digg.fish", target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/digg.fish"

  # The release binary is not Developer ID-signed. Match the other CLI casks
  # in this tap by clearing the download quarantine after Homebrew stages it.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/digg"]
    end
  end
end
EOF
